version: '3'
services:
  naviloper-app:
    build:
      context: .
      dockerfile: .docker/DockerFile
    container_name: naviloper-app
    volumes:
      - './:/usr/src/app'
    restart: on-failure
    user: 1000:1000
    depends_on:
      - naviloper-nginx
      - naviloper-db

  naviloper-nginx:
    container_name: naviloper-nginx
    image: nginx:1.18.0-alpine
    ports:
      - "8080:80"
    restart: always
    volumes:
      - './:/usr/src/app'
      - './.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'

  naviloper-db:
    container_name: naviloper-db
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: naviloper_db
      MYSQL_USER: naviloper_user
      MYSQL_PASSWORD: naviloper_pass
    volumes:
      - ./../naviloper_db:/var/lib/mysql
    restart: on-failure