palette:
  top: '#016b83'
  bottom: '#016b83'
  bg: '#ffffff'
  sidebar: '#ffffff'
  sidebarborders: '#cccccc'
  footer: '#016b83'
  titleslogan: '#000000'
  text: '#4a4a4a'
  link: '#019dbf'
logo: 'public://color/bartik-9b5b8b89/logo.svg'
stylesheets:
  - 'public://color/bartik-9b5b8b89/colors.css'
files:
  - 'public://color/bartik-9b5b8b89/logo.svg'
  - 'public://color/bartik-9b5b8b89/colors.css'
